version: 0.1

workflows:
  main:
    jobs:
    - build

jobs:
  build:
    steps:
    - clone

    - cache_restore:
        path: node_modules
        key: 'npm-{{ hash "package-lock.json" }}-v1'

    - run: wget -qO- https://api.wodby.com/api/v1/get/cli?version=2.0 | sh
    - run: wodby ci init $WODBY_BUILD_ID
    - run: wodby ci run -i wodby/node -- npm install

    - cache_save:
        key: 'npm-{{ hash "package-lock.json" }}-v1'
        path: node_modules

    - run: wodby ci build nginx
    - run: wodby ci release
    - run: wodby ci deploy
